# This workflow handles releasing all of the packages in samples.

name: publish

on: workflow_dispatch  # Manually trigger.

permissions:
  contents: write  # For checkout and tag.
  packages: write  # For publish.

jobs:
  publish:
    runs-on: ubuntu-latest

    # Environment specific to releasing so we can isolate the npm token.
    environment: release  

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: NPM install
      # Use CI so that we don't update dependencies in this step.
      run: npm ci

    - name: Build
      run: npm run build -- -- -- --skip-lint

    - name: Test
      run: npm run test -- -- -- --skip-lint

    - name: Publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.RELEASE_BACKED_NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: lerna publish --conventional-commits --create-release github --yes
